/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Model_pizzariaclaudiaerica.Cliente;
import Model_pizzariaclaudiaerica.TabelaCliente;
import Model_pizzariaclaudiaerica.Usability;
import Relatorio.Relatorio;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clau
 */
public class jifCadastro extends javax.swing.JInternalFrame {
    private final TabelaCliente modelo = new TabelaCliente();
    private final List<Cliente> listaDeClientes = new ArrayList();
    private int linhaClicada=-1;
    
    /**
     * Creates new form jifCadastro
     */
    public jifCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTid = new javax.swing.JTextField();
        jLcod = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jTsobrenome = new javax.swing.JTextField();
        jLsobrenome = new javax.swing.JLabel();
        jLtelefone = new javax.swing.JLabel();
        jFTtelefone = new javax.swing.JFormattedTextField();
        jLemail = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jRBnovocadastro = new javax.swing.JRadioButton();
        jRBatualizarcadastro = new javax.swing.JRadioButton();
        bsalvar = new javax.swing.JButton();
        blistar = new javax.swing.JButton();
        bsair = new javax.swing.JButton();
        jTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLcod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLcod.setForeground(new java.awt.Color(51, 0, 255));
        jLcod.setText("ID:");

        jLnome.setText("Nome:");

        jLsobrenome.setText("Sobrenome:");

        jLtelefone.setText("Telefone:");

        try {
            jFTtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55 (##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLemail.setText("E-mail:");

        buttonGroup1.add(jRBnovocadastro);
        jRBnovocadastro.setForeground(new java.awt.Color(0, 0, 255));
        jRBnovocadastro.setText("Novo Cadastro");

        buttonGroup1.add(jRBatualizarcadastro);
        jRBatualizarcadastro.setForeground(new java.awt.Color(0, 0, 255));
        jRBatualizarcadastro.setText("Atualizar Cadastro");

        bsalvar.setBackground(new java.awt.Color(153, 204, 255));
        bsalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsalvar.setText("Salvar");
        bsalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsalvarMouseClicked(evt);
            }
        });

        blistar.setBackground(new java.awt.Color(255, 204, 204));
        blistar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        blistar.setText("Listar");
        blistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blistarMouseClicked(evt);
            }
        });

        bsair.setBackground(new java.awt.Color(255, 255, 204));
        bsair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsair.setText("Sair");
        bsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsairActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Telefone", "Email"
            }
        ));
        jTable.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTable)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLnome, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(jLcod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTnome, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                            .addComponent(jTid)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFTtelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLemail, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(blistar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTemail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBnovocadastro)
                                        .addGap(60, 60, 60)
                                        .addComponent(jRBatualizarcadastro))
                                    .addComponent(jTsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(bsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcod)
                    .addComponent(jRBnovocadastro)
                    .addComponent(jRBatualizarcadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsobrenome)
                    .addComponent(jTsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtelefone)
                    .addComponent(jFTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLemail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalvar)
                    .addComponent(blistar)
                    .addComponent(bsair))
                .addGap(18, 18, 18)
                .addComponent(jTable, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(200, 20, 732, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //quando essa tela de cadastro abrir a variavel vai se tornar verdadeira e não falsa 
        jfprincipal.cadastro = true;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
        
        jfprincipal.cadastro = false; // variavel deve se tornar falsa para que quando fechar a tela poder abrer novamente
        dispose(); //usar toda vez que for sair
        // TODO add your handling code here:
    }//GEN-LAST:event_bsairActionPerformed

    private void bsalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsalvarMouseClicked

        String id = jTid.getText().trim();
        String nome = jTnome.getText().trim();
        String sobrenome = jTsobrenome.getText().trim();
        String telefone = jFTtelefone.getText().trim();
        String email = jTemail.getText().trim();
        //Cliente c = null;
        
        DefaultTableModel val = (DefaultTableModel) jTable1.getModel();
            val.addRow(new String[]{id, nome, sobrenome, telefone, email});
        
            
            jTid.setText("");
            jTnome.setText("");
            jTsobrenome.setText("");
            jFTtelefone.setText("");
            jTemail.setText("");
            
            jTnome.requestFocus(); //limpa os campos e retorna na caixa de texto do nome
        //c = new Cliente (id, nome, sobrenome, telefone, email);
        
        //Cliente cliente = new Cliente(id,nome,sobrenome,telefone, email);
        //listaDeClientes.add(cliente);
        //modelo.adicionaCliente(cliente);
       // if (c != null)
            
        //Usability.list.add(c);
        
        //String relatorio = Relatorio.gerarRelatorio(Usability.list);
        
        
        //jTcadastro.setText(relatorio);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bsalvarMouseClicked

    private void blistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blistarMouseClicked

        modelo.atualizarTabela(listaDeClientes);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_blistarMouseClicked

    
public static void main(String args[]) {
        
        /* Cliente */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jifCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jifCadastro().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blistar;
    private javax.swing.JButton bsair;
    private javax.swing.JButton bsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFTtelefone;
    private javax.swing.JLabel jLcod;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLsobrenome;
    private javax.swing.JLabel jLtelefone;
    private javax.swing.JRadioButton jRBatualizarcadastro;
    private javax.swing.JRadioButton jRBnovocadastro;
    private javax.swing.JScrollPane jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTsobrenome;
    // End of variables declaration//GEN-END:variables
}
